### ISSUE TITLE
How to generate texture mesh

### ISSUE THREAD

**Issue by zhixiongzuo** [l1346792580123/diff#1]
After optiming, there is a tex.pt, how to convert it to textured mesh ?

**Comment by l1346792580123** [comment]
Please follow this instruction https://steamcommunity.com/sharedfiles/filedetails/?id=1265761945 to generate texture mesh. First you need to use blender to unwarp the mesh, then you can use meshlab to put the vertex colors on a texture.

**Comment by LHXhh** [comment]
作者您好，感谢您精彩的工作，我按照[ https://steamcommunity.com/sharedfiles/filedetails/?id=1265761945](url)，得到的color图是全灰的。
![77_uv_color](https://github.com/l1346792580123/diff/assets/102360620/1a5ddf55-0fb7-4ed7-9168-16edf1e700f9)
我想用openmvs和diff得到的texture mesh进行纹理质量评价，但现在只得到diff的OBJ，还缺少对应的纹理图，我该怎么做呢，真诚地希望能够得到您的帮助！
