### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by LHXhh** [l1346792580123/diff#3]
您好，我想请问下您分享的datasets是需要港科大的账户才能登陆吗？我直接用github账户访问出现了异常，您能够帮助下我吗，谢谢。

**Comment by l1346792580123** [comment]
mvsdf的作者更新的地址，现在新的地址为https://huggingface.co/datasets/jzhangbs/mvsdf_dtu。

**Comment by LHXhh** [comment]
好的，太感谢了！
